//! State-machine documentation generation (ADR-0016 X5). Walks the composed
//! service registry, derives each machine's transition graph from its rules'
//! declared `active_states` / `transitions` (plus the framework `global-call`
//! machine), and renders one Mermaid `stateDiagram-v2` per machine. Both the
//! `xtask state-machine-docs` subcommand and the CI freshness test call
//! [`render_registry`], so the committed diagrams cannot silently drift.

use std::collections::BTreeSet;

use super::invariants::GLOBAL_CALL_MACHINE;
use super::service::ServiceDef;

/// A machine's transition graph: a deterministic (sorted, deduped) set of state
/// labels and `(from, to)` edges.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MachineGraph {
    pub id: String,
    pub states: Vec<String>,
    pub edges: Vec<(String, String)>,
}

fn graph_from(
    id: &str,
    states: impl IntoIterator<Item = String>,
    edges: impl IntoIterator<Item = (String, String)>,
) -> MachineGraph {
    let mut state_set: BTreeSet<String> = states.into_iter().collect();
    let edge_set: BTreeSet<(String, String)> = edges.into_iter().collect();
    for (a, b) in &edge_set {
        state_set.insert(a.clone());
        state_set.insert(b.clone());
    }
    MachineGraph {
        id: id.to_string(),
        states: state_set.into_iter().collect(),
        edges: edge_set.into_iter().collect(),
    }
}

/// The framework global call machine — projected from `CallModelState`
/// (ADR-0016 X2), so its edges are the lifecycle, not rule-declared.
pub fn global_call_graph() -> MachineGraph {
    graph_from(
        GLOBAL_CALL_MACHINE.as_str(),
        ["Active", "Terminating", "Terminated"].into_iter().map(str::to_string),
        [
            ("Active", "Terminating"),
            ("Active", "Terminated"),
            ("Terminating", "Terminated"),
        ]
        .into_iter()
        .map(|(a, b)| (a.to_string(), b.to_string())),
    )
}

/// Derive a service machine's graph from its rules' declaration columns.
pub fn service_graph(def: &ServiceDef) -> MachineGraph {
    let rules = (def.rules)();
    let mut states = Vec::new();
    let mut edges = Vec::new();
    for r in &rules {
        if r.machine.as_ref().map(|m| m.as_str()) != Some(def.id) {
            continue; // not this machine's rule (defensive; checked elsewhere).
        }
        for s in r.active_states {
            states.push(s.as_str().to_string());
        }
        for (from, to) in r.transitions {
            states.push(from.as_str().to_string());
            states.push(to.as_str().to_string());
            edges.push((from.as_str().to_string(), to.as_str().to_string()));
        }
    }
    graph_from(def.id, states, edges)
}

/// Render a machine graph as a committed-diagram markdown document.
pub fn render_mermaid(g: &MachineGraph) -> String {
    let mut out = String::new();
    out.push_str(&format!("# State machine: `{}`\n\n", g.id));
    out.push_str(
        "<!-- GENERATED by `cargo run -p xtask -- state-machine-docs` from the composed\n     \
         service registry (ADR-0016). Do not edit by hand; regenerate instead. -->\n\n",
    );
    out.push_str("```mermaid\nstateDiagram-v2\n");
    for s in &g.states {
        out.push_str(&format!("    {s}\n"));
    }
    for (from, to) in &g.edges {
        out.push_str(&format!("    {from} --> {to}\n"));
    }
    out.push_str("```\n");
    out
}

/// Render the whole registry: the framework `global-call` machine first, then
/// one document per registered service. Returns `(machine_id, markdown)` pairs —
/// the doc file is `docs/sm/<machine_id>.md`.
pub fn render_registry(services: &[ServiceDef]) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let g = global_call_graph();
    out.push((g.id.clone(), render_mermaid(&g)));
    for def in services {
        let g = service_graph(def);
        out.push((g.id.clone(), render_mermaid(&g)));
    }
    out
}

/// Static validation (ADR-0016 X5): every rule a service contributes must belong
/// to that service's own machine. (State-label membership in the machine's enum
/// is already a compile-time guarantee — `sm_rule!` references enum variants.)
/// Returns the list of violations, empty when the registry is well-formed.
pub fn check_registry(services: &[ServiceDef]) -> Vec<String> {
    let mut errs = Vec::new();
    for def in services {
        for r in (def.rules)() {
            match r.machine.as_ref().map(|m| m.as_str()) {
                Some(m) if m == def.id => {}
                Some(m) => errs.push(format!(
                    "service '{}' contributes rule '{}' bound to a foreign machine '{}'",
                    def.id, r.id, m
                )),
                None => errs.push(format!(
                    "service '{}' contributes machine-less rule '{}' (use a core rule instead)",
                    def.id, r.id
                )),
            }
        }
    }
    errs
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rules::model::{Match, RuleDefinition, RuleHandleResult, SERVICE_LAYER};
    use crate::rules::ServiceSeed;
    use call::{MachineId, StateLabel};

    static STUB_ACTIVE: [StateLabel; 1] = [StateLabel::new("S0")];
    static STUB_TRANS: [(StateLabel, StateLabel); 1] =
        [(StateLabel::new("S0"), StateLabel::new("S1"))];

    fn stub_handle(_: &crate::rules::RuleContext) -> Option<RuleHandleResult> {
        Some(RuleHandleResult::new(vec![]))
    }
    fn stub_rules() -> Vec<RuleDefinition> {
        vec![RuleDefinition {
            id: "stub-advance",
            layer: SERVICE_LAYER,
            overrides: &[],
            matcher: Match::request().method("INFO"),
            handle: stub_handle,
            machine: Some(MachineId::new("stub")),
            active_states: &STUB_ACTIVE,
            transitions: &STUB_TRANS,
        }]
    }
    fn stub_init(_: &call::Call) -> Option<ServiceSeed> {
        None
    }
    fn stub_def() -> ServiceDef {
        ServiceDef { id: "stub", init: stub_init, rules: stub_rules }
    }

    fn assert_well_formed_mermaid(md: &str, machine: &str) {
        assert!(md.starts_with(&format!("# State machine: `{machine}`")), "title");
        assert!(md.contains("```mermaid\nstateDiagram-v2\n"), "mermaid fence + diagram type");
        assert!(md.trim_end().ends_with("```"), "closing fence");
    }

    #[test]
    fn global_call_diagram_is_non_empty_and_well_formed() {
        let g = global_call_graph();
        assert_eq!(g.id, "global-call");
        assert_eq!(g.states, vec!["Active", "Terminated", "Terminating"]);
        assert!(g.edges.contains(&("Active".into(), "Terminating".into())));
        let md = render_mermaid(&g);
        assert_well_formed_mermaid(&md, "global-call");
        assert!(md.contains("Active --> Terminating"));
    }

    #[test]
    fn stub_service_diagram_is_derived_from_rules() {
        let g = service_graph(&stub_def());
        assert_eq!(g.id, "stub");
        assert_eq!(g.states, vec!["S0", "S1"]);
        assert_eq!(g.edges, vec![("S0".to_string(), "S1".to_string())]);
        let md = render_mermaid(&g);
        assert_well_formed_mermaid(&md, "stub");
        assert!(md.contains("S0 --> S1"));
    }

    #[test]
    fn render_registry_prepends_global_call() {
        let rendered = render_registry(&[stub_def()]);
        let ids: Vec<&str> = rendered.iter().map(|(id, _)| id.as_str()).collect();
        assert_eq!(ids, vec!["global-call", "stub"]);
    }

    #[test]
    fn check_registry_flags_foreign_machine() {
        // A service whose rules belong to a different machine is a violation.
        fn foreign_rules() -> Vec<RuleDefinition> {
            stub_rules() // machine == "stub"
        }
        let bad = ServiceDef { id: "other", init: stub_init, rules: foreign_rules };
        let errs = check_registry(&[bad]);
        assert_eq!(errs.len(), 1, "foreign-machine rule flagged");
        // A self-consistent service passes.
        assert!(check_registry(&[stub_def()]).is_empty());
    }
}
