//! Fluent, auto-generating harness — the primary scenario style.
//!
//! Same full dialog as `alice_calls_bob.rs` (INVITE/180/200/ACK/BYE/200), but
//! **no message is hand-authored**: every header (Via + fresh branch, From/To
//! tags, Call-ID, CSeq, Contact, Max-Forwards, Content-*) is generated by the
//! agents via `sip_message::generators`, and the dialog state (remote tag,
//! remote target, CSeq) is tracked across calls. The test then parses the
//! **recording** and asserts the auto-generated CSeq/dialog came out correct —
//! i.e. the harness, not the test author, got the SIP right.

use std::path::PathBuf;

use scenario_harness::Harness;
use sip_message::parser::custom::CustomParser;
use sip_message::{SipMessage, SipParser};

const SDP_OFFER: &str = "v=0\r\no=alice 2890 2890 IN IP4 127.0.0.1\r\ns=-\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\nm=audio 49170 RTP/AVP 0\r\na=rtpmap:0 PCMU/8000\r\n";
const SDP_ANSWER: &str = "v=0\r\no=bob 2890 2890 IN IP4 127.0.0.1\r\ns=-\r\nc=IN IP4 127.0.0.1\r\nt=0 0\r\nm=audio 49180 RTP/AVP 0\r\na=rtpmap:0 PCMU/8000\r\n";

fn parse(raw: &[u8]) -> SipMessage {
    CustomParser::new()
        .parse(raw)
        .unwrap_or_else(|e| panic!("entry did not parse: {e}\n{}", String::from_utf8_lossy(raw)))
}

fn assert_request(raw: &[u8], method: &str, cseq_seq: u32) {
    match parse(raw) {
        SipMessage::Request(r) => {
            assert_eq!(r.method, method);
            assert_eq!(r.cseq.method, method, "CSeq method == request method");
            assert_eq!(r.cseq.seq, cseq_seq, "CSeq seq for {method}");
        }
        other => panic!("expected {method} request, got {other:?}"),
    }
}

fn assert_response(raw: &[u8], status: u16, cseq_seq: u32, cseq_method: &str) {
    match parse(raw) {
        SipMessage::Response(r) => {
            assert_eq!(r.status, status);
            assert_eq!(r.cseq.seq, cseq_seq, "echoed CSeq seq for {status}");
            assert_eq!(r.cseq.method, cseq_method, "echoed CSeq method for {status}");
        }
        other => panic!("expected {status} response, got {other:?}"),
    }
}

#[tokio::test]
async fn full_dialog_auto_generated() {
    let h = Harness::new("alice-calls-bob").describe(
        "Full one-call dialog generated by the fluent DSL: alice.invite(bob) → \
         180 → 200 → ack() → bye(). No headers are hand-authored; CSeq, tags, \
         Via branches and routing are all filled in by the harness.",
    );
    let alice = h.agent("alice", "127.0.0.1:5060").await;
    let bob = h.agent("bob", "127.0.0.1:5070").await;

    // --- the scenario: read it top-to-bottom, no SIP headers in sight --------
    let mut call = alice.invite(&bob).with_sdp(SDP_OFFER).send().await;

    let mut uas = bob.receive("INVITE").await;
    // The UAS can inspect what it got — e.g. that the offer arrived.
    assert!(
        uas.request().body.starts_with(b"v=0"),
        "INVITE should carry the SDP offer body"
    );
    uas.respond(180, "Ringing").await;
    call.expect(180).await;

    uas.respond(200, "OK").with_sdp(SDP_ANSWER).send().await;
    let ok = call.expect(200).await;
    assert!(ok.to.tag.is_some(), "200 OK must carry the UAS To-tag");

    let mut dialog = call.ack().await;
    bob.receive("ACK").await;

    let mut bye = dialog.bye().await;
    bob.receive("BYE").await.respond(200, "OK").await;
    bye.expect(200).await;

    // --- verify the recording -------------------------------------------------
    let report = h.finish().await;
    let entries = report.entries();
    assert_eq!(entries.len(), 6, "entries: {entries:#?}");
    assert!(entries.iter().all(|e| e.delivered));

    let alice_addr = "127.0.0.1:5060".parse().unwrap();
    let bob_addr = "127.0.0.1:5070".parse().unwrap();
    let dirs: Vec<_> = entries.iter().map(|e| (e.from, e.to)).collect();
    assert_eq!(
        dirs,
        vec![
            (alice_addr, bob_addr), // INVITE
            (bob_addr, alice_addr), // 180
            (bob_addr, alice_addr), // 200 (INVITE)
            (alice_addr, bob_addr), // ACK
            (alice_addr, bob_addr), // BYE
            (bob_addr, alice_addr), // 200 (BYE)
        ]
    );

    // The auto-generated CSeq numbering is correct: 1 INVITE → 1 ACK → 2 BYE,
    // responses echo their request's CSeq.
    assert_request(&entries[0].raw, "INVITE", 1);
    assert_response(&entries[1].raw, 180, 1, "INVITE");
    assert_response(&entries[2].raw, 200, 1, "INVITE");
    assert_request(&entries[3].raw, "ACK", 1);
    assert_request(&entries[4].raw, "BYE", 2);
    assert_response(&entries[5].raw, 200, 2, "BYE");

    // Dialog correctness: the INVITE has no To-tag; every later message shares
    // one stable To-tag (bob's) and one Call-ID.
    let invite = parse(&entries[0].raw);
    let SipMessage::Request(invite) = invite else { unreachable!() };
    assert!(invite.to.tag.is_none(), "initial INVITE must have no To-tag");
    let call_id = invite.call_id.clone();
    let to_tag = match parse(&entries[2].raw) {
        SipMessage::Response(r) => r.to.tag.clone().expect("200 has To-tag"),
        _ => unreachable!(),
    };
    for e in &entries[1..] {
        let m = parse(&e.raw);
        let (cid, tag) = match &m {
            SipMessage::Request(r) => (r.call_id.clone(), r.to.tag.clone()),
            SipMessage::Response(r) => (r.call_id.clone(), r.to.tag.clone()),
        };
        assert_eq!(cid, call_id, "Call-ID continuity");
        assert_eq!(tag.as_deref(), Some(to_tag.as_str()), "stable To-tag");
    }

    // --- reports still render from the recording -----------------------------
    let out = PathBuf::from(env!("CARGO_TARGET_TMPDIR")).join("fluent-dialog");
    let _ = std::fs::remove_dir_all(&out);
    scenario_harness::report::write_all(&report, &out).expect("write reports");

    let global = std::fs::read_to_string(out.join("alice-calls-bob.global.txt")).unwrap();
    assert!(global.contains("INVITE sip:bob@127.0.0.1:5070 SIP/2.0"));
    assert!(global.contains("180 Ringing"));
    assert!(global.contains("ACK sip:bob@127.0.0.1:5070 SIP/2.0"));
    assert!(global.contains("BYE sip:bob@127.0.0.1:5070 SIP/2.0"));
    assert!(global.contains("CSeq: 1 ACK"));
    assert!(global.contains("CSeq: 2 BYE"));

    let html = std::fs::read_to_string(out.join("alice-calls-bob.html")).unwrap();
    assert!(html.contains("addEventListener('click'"), "clickable SVG handler present");
}
