//! Composing a `send` step's message (`PCAP2TEST_PIVOT_V3.md` §14 item 3).
//!
//! A send emits **exactly what `msg` states, plus tier-1 regeneration, plus any
//! run-config injected headers, plus any accessor substitution. Nothing else.**
//! This module owns the "plus" list and hands the stack a
//! [`MessageTemplate`](sip_message::MessageTemplate): tier-1 (Via and branch,
//! Call-ID, tags, CSeq numbering, Max-Forwards, Content-Length, Contact,
//! route sets) is regenerated by the stack and never stored here.
//!
//! No SIP is parsed in this crate: the frozen headers are already `{name,
//! value}` pairs — `sip-message` did the parsing at extraction — and this
//! module reassembles them.
//!
//! A tier-2 ref resolves through the lane's identity binding where it is
//! positional, and rides verbatim where the document froze it. A `${…}` is
//! substituted wherever it appears, including inside a frozen value: §8.1 states
//! there is no position where an accessor is literal text.

use std::collections::BTreeMap;
use std::path::Path;

use pivot_schema::body::Body;
use pivot_schema::bundle::RunConfig;
use pivot_schema::msg::{MsgSpec, Ref};
use sip_message::{HeaderName, MessageTemplate, Method, MultipartPart, TemplateHeader};

use crate::deviation::StepEffects;
use crate::media::Booking;
use crate::resolve::{ResolveError, Resolver};

/// Why a step's message could not be composed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum RenderError {
    /// A `${…}` in the message could not be resolved at emission time.
    Accessor { site: String, detail: String },
    /// A positional tier-2 ref naming a position the run cannot resolve to an
    /// identity.
    UnresolvedPosition { site: String, pos: String },
    /// The body resource could not be read.
    BodyUnreadable { reference: String, detail: String },
    /// A single-part body reference that declares neither SDP rewrite tags nor a
    /// content type: labelling it `application/sdp` would be a guess.
    BodyUnlabelled { reference: String },
    /// A multipart body that cannot be framed: the container names no multipart
    /// type, states no parts, or states a boundary a part's payload holds.
    MultipartUnframable { detail: String },
    /// A part a header references by `cid:` (§8.3 `cid-linked`) that states no
    /// `content-id` of its own: emitting it would leave the referencing header
    /// pointing at nothing (RFC 5621 §3).
    MultipartCidUnstated { reference: String, headers: Vec<String> },
    /// A `malformed-header` deviation naming a header the step does not carry:
    /// it would reproduce nothing.
    MalformedHeaderAbsent { site: String, header: String },
    /// The message states neither a method nor a status.
    NoStartLine,
}

impl std::fmt::Display for RenderError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            RenderError::Accessor { site, detail } => write!(f, "{site}: {detail}"),
            RenderError::UnresolvedPosition { site, pos } => {
                write!(f, "{site}: position {pos:?} resolves to no identity the lane bound")
            }
            RenderError::BodyUnreadable { reference, detail } => {
                write!(f, "body resource {reference:?}: {detail}")
            }
            RenderError::BodyUnlabelled { reference } => write!(
                f,
                "body resource {reference:?} declares neither SDP rewrite tags nor a content type"
            ),
            RenderError::MultipartUnframable { detail } => {
                write!(f, "the multipart body cannot be framed: {detail}")
            }
            RenderError::MultipartCidUnstated { reference, headers } => write!(
                f,
                "multipart part {reference:?} is referenced by cid: from {}, and the document \
                 states no content-id to emit it under",
                headers.join(", ")
            ),
            RenderError::MalformedHeaderAbsent { site, header } => write!(
                f,
                "{site}: a malformed-header deviation names {header:?}, which the step does not carry"
            ),
            RenderError::NoStartLine => write!(f, "the message states neither a method nor a status"),
        }
    }
}

impl From<(&str, ResolveError)> for RenderError {
    fn from((site, error): (&str, ResolveError)) -> Self {
        RenderError::Accessor { site: site.to_string(), detail: error.to_string() }
    }
}

/// A composed message: the template the stack emits, plus the tier-2 URIs it
/// regenerates the dialog identity around.
#[derive(Debug, Clone, PartialEq)]
pub struct Rendered {
    pub template: MessageTemplate,
    pub ruri: Option<String>,
    pub from: Option<String>,
    pub to: Option<String>,
}

/// How a lane turns a tier-2 position and a dial form into a URI. The
/// composition is the LANE's — a trunk-composed dialled form is a numbering-plan
/// fact, not a SIP one — so the interpreter asks rather than builds.
pub trait UriComposer {
    /// The URI for a positional ref. `is_ruri` selects the host: a Request-URI
    /// is addressed at the system under test, a From/To at the lane's domain.
    fn compose(&self, pos: &str, form: Option<&str>, is_ruri: bool) -> Option<String>;
    /// The URI for a value the document froze. `kind` is the ref's own class
    /// token: present means the frozen value is a whole ADDRESS (a URI minus
    /// its scheme), absent means a bare userpart the lane hosts.
    fn frozen(&self, value: &str, kind: Option<&str>, is_ruri: bool) -> String;
}

/// Everything composing a message needs beyond the message itself: the run's
/// own state, the lane's configuration and the deviations the step carries.
pub struct Context<'a> {
    pub resolver: &'a Resolver<'a>,
    pub config: &'a RunConfig,
    pub effects: &'a StepEffects,
    pub composer: &'a dyn UriComposer,
    /// Where a body resource reference resolves from.
    pub base_dir: &'a Path,
    /// The lane's media plane: what a rewritten SDP body's `c=` and `m=` lines
    /// carry.
    pub media: &'a Booking,
    /// The leg this send rides, which is what a media port is booked against.
    pub leg: &'a str,
    /// The lane directives for the CALL this step dials, where it dials one —
    /// empty on every other step. A call's egress is its own (§4.3).
    pub call_headers: &'a BTreeMap<String, String>,
}

/// Compose `msg` for the wire.
pub fn render(msg: &MsgSpec, site: &str, cx: &Context<'_>) -> Result<Rendered, RenderError> {
    let Context { resolver, config, effects, composer, base_dir, media, leg, call_headers } = *cx;
    let mut headers: Vec<TemplateHeader> = Vec::new();
    for header in &msg.headers {
        let name = resolver.text(&header.name).map_err(|e| RenderError::from((site, e)))?;
        let value = resolver.text(&header.value).map_err(|e| RenderError::from((site, e)))?;
        // A frozen header already rides EXACTLY as stored, so a deliberately
        // malformed one needs no special emission — but the deviation must find
        // the header it claims to break, or it silently reproduces nothing.
        headers.push(TemplateHeader::frozen(name, value));
    }
    for broken in &effects.malformed_headers {
        if !headers.iter().any(|h| h.name.eq_ignore_ascii_case(broken)) {
            return Err(RenderError::MalformedHeaderAbsent {
                site: site.to_string(),
                header: broken.clone(),
            });
        }
    }
    // Lane artifacts, stamped last so a document header of the same name wins:
    // an injected header is the lane's own, never part of the choreography.
    // This call's own directive goes on FIRST, so the more specific statement
    // wins over the run-wide one of the same name.
    for (name, value) in call_headers.iter().chain(&config.injected_headers) {
        if !headers.iter().any(|h| h.name.eq_ignore_ascii_case(name)) {
            headers.push(TemplateHeader::frozen(name.clone(), value.clone()));
        }
    }

    let (body, content_type) = match &msg.body {
        None => (Vec::new(), None),
        Some(body) => load_body(body, base_dir, media, leg)?,
    };
    if let Some(ct) = &content_type {
        if !headers.iter().any(|h| HeaderName::ContentType.matches(&h.name)) {
            headers.push(TemplateHeader::frozen("Content-Type", ct.clone()));
        }
    }

    let template = match (&msg.method, msg.status) {
        (Some(method), None) => MessageTemplate::request(Method::from_wire(method), headers, body),
        (None, Some(status)) => {
            MessageTemplate::response(status, msg.reason.clone().unwrap_or_default(), headers, body)
        }
        _ => return Err(RenderError::NoStartLine),
    };

    Ok(Rendered {
        template,
        ruri: uri(msg.ruri.as_ref(), site, "ruri", true, resolver, composer)?,
        from: uri(msg.from.as_ref(), site, "from", false, resolver, composer)?,
        to: uri(msg.to.as_ref(), site, "to", false, resolver, composer)?,
    })
}

/// One tier-2 ref, resolved.
fn uri(
    r: Option<&Ref>,
    site: &str,
    what: &str,
    is_ruri: bool,
    resolver: &Resolver<'_>,
    composer: &dyn UriComposer,
) -> Result<Option<String>, RenderError> {
    let Some(r) = r else { return Ok(None) };
    let site = format!("{site} {what}");
    match r {
        Ref::Positional(p) => {
            let pos = resolver.text(&p.pos).map_err(|e| RenderError::from((site.as_str(), e)))?;
            let form = match &p.form {
                None => None,
                Some(f) => {
                    Some(resolver.text(f).map_err(|e| RenderError::from((site.as_str(), e)))?)
                }
            };
            composer
                .compose(&pos, form.as_deref(), is_ruri)
                .map(Some)
                .ok_or(RenderError::UnresolvedPosition { site, pos })
        }
        Ref::Frozen(f) => {
            let value =
                resolver.text(&f.frozen).map_err(|e| RenderError::from((site.as_str(), e)))?;
            Ok(Some(composer.frozen(&value, f.kind.as_deref(), is_ruri)))
        }
    }
}

/// Which of §8.3's rewrite tokens a body states. Each token gates its OWN line
/// kind, so a document asking for one never gets the other.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct Rewrite {
    /// `c=addr`: every connection line takes the lane's media address.
    addr: bool,
    /// `m=port`: every active media line takes the port the lane booked it.
    port: bool,
}

impl Rewrite {
    fn of(tags: &[String]) -> Self {
        Rewrite {
            addr: tags.iter().any(|tag| tag == "c=addr"),
            port: tags.iter().any(|tag| tag == "m=port"),
        }
    }

    /// Whether the payload is rewritten at all — which is what declares it SDP.
    fn any(self) -> bool {
        self.addr || self.port
    }
}

/// Load a body resource and derive its content type. SDP (declared by its
/// rewrite tags, direct or as a part) is the ONE content rewritten, and only the
/// lines its tokens name, and only where the lane's booking answers them — a
/// verbatim booking leaves the body as stored under the type the tags declare;
/// every other payload, every part's `Content-ID` and every part entity header
/// rides exactly as stored (§8.3). A single reference declaring neither rewrite
/// tags nor a type is REFUSED rather than mislabelled.
fn load_body(
    body: &Body,
    base_dir: &Path,
    media: &Booking,
    leg: &str,
) -> Result<(Vec<u8>, Option<String>), RenderError> {
    match body {
        // A shape is an expect-side assertion, never a send body.
        Body::Shape(_) => Ok((Vec::new(), None)),
        // The parts are decomposed on disk and each rides byte-exact; the
        // FRAMING is regenerated, boundary included, because the document
        // stores the container type with its boundary stripped (§8.3).
        Body::Multipart(m) => {
            let mut parts: Vec<MultipartPart> = Vec::new();
            // One stream index runs across the whole BODY: two rewritten parts
            // describe two streams of one session, never two stream zeroes.
            let mut stream = 0usize;
            for part in &m.multipart.parts {
                if !part.cid_linked.is_empty() && part.content_id.is_none() {
                    return Err(RenderError::MultipartCidUnstated {
                        reference: part.reference.clone(),
                        headers: part.cid_linked.clone(),
                    });
                }
                let bytes = read(base_dir, &part.reference)?;
                let rewrite = Rewrite::of(&part.rewrite);
                let payload = if rewrite.any() {
                    let text = String::from_utf8_lossy(&bytes);
                    rewrite_sdp(&text, rewrite, media, leg, &mut stream).into_bytes()
                } else {
                    bytes
                };
                // Content-Type is the composer's own first line; the stored
                // `Content-ID` leads the rest so a `cid:` reference resolves,
                // then the part's other entity headers in stored order.
                let mut composed = MultipartPart::new(part.content_type.clone(), payload);
                if let Some(content_id) = &part.content_id {
                    composed = composed.with_header("Content-ID", content_id.clone());
                }
                for header in &part.headers {
                    composed = composed.with_header(header.name.clone(), header.value.clone());
                }
                parts.push(composed);
            }
            let composed = sip_message::compose_multipart(&m.multipart.content_type, &parts)
                .map_err(|e| RenderError::MultipartUnframable { detail: e.to_string() })?;
            Ok((composed.body, Some(composed.content_type)))
        }
        Body::Resource(r) => {
            let bytes = read(base_dir, &r.reference)?;
            let rewrite = Rewrite::of(&r.rewrite);
            if !rewrite.any() {
                return match &r.content_type {
                    Some(ct) => Ok((bytes, Some(ct.clone()))),
                    None => Err(RenderError::BodyUnlabelled { reference: r.reference.clone() }),
                };
            }
            let text = String::from_utf8_lossy(&bytes).into_owned();
            // Rewriting the payload never re-labels it: a stated type wins, so
            // an SDP body captured with parameters replays under them.
            let content_type =
                r.content_type.clone().unwrap_or_else(|| "application/sdp".to_string());
            let mut stream = 0usize;
            let payload = rewrite_sdp(&text, rewrite, media, leg, &mut stream).into_bytes();
            Ok((payload, Some(content_type)))
        }
    }
}

fn read(base_dir: &Path, reference: &str) -> Result<Vec<u8>, RenderError> {
    let path = base_dir.join(reference);
    std::fs::read(&path).map_err(|e| RenderError::BodyUnreadable {
        reference: reference.to_string(),
        detail: format!("{}: {e}", path.display()),
    })
}

/// Rewrite an SDP body's lane-owned fields — connection lines under `c=addr`,
/// media ports under `m=port` — keeping the framing byte-for-byte otherwise.
/// The line grammar is `sip_message::sdp`'s; this binds it to the lane's
/// booking: `stream` carries the body's active-media index across the body, so
/// the i-th active `m=` line takes the i-th port booked for `leg`, and a
/// rejected (port-0) stream consumes no index. A booking that answers no token
/// (a lane without media) leaves every line as stored.
fn rewrite_sdp(
    sdp: &str,
    rewrite: Rewrite,
    media: &Booking,
    leg: &str,
    stream: &mut usize,
) -> String {
    let addr = if rewrite.addr { media.addr() } else { None };
    sip_message::rewrite_connection_and_ports(sdp, addr, |pairs| {
        if !rewrite.port {
            return None;
        }
        let port = media.port(leg, *stream, pairs);
        *stream += 1;
        port
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::state::RunState;
    use pivot_schema::bundle::{ClockMode, IdentityBindings};
    use pivot_schema::msg::{Header, PositionalRef};
    use sip_message::header::Uri;

    struct TestComposer;

    impl UriComposer for TestComposer {
        fn compose(&self, pos: &str, form: Option<&str>, is_ruri: bool) -> Option<String> {
            let host = if is_ruri { "10.0.0.9:5080" } else { "lane.invalid" };
            match (pos, form) {
                ("caller", _) => Some(format!("sip:0009001@{host}")),
                ("called[0][0]", Some("trunk-composed")) => {
                    Some(format!("sip:+1999999900004@{host}"))
                }
                _ => None,
            }
        }
        fn frozen(&self, value: &str, kind: Option<&str>, is_ruri: bool) -> String {
            let host = if is_ruri { "10.0.0.9:5080" } else { "lane.invalid" };
            if Uri::value_has_scheme(value) {
                value.to_string()
            } else if kind.is_some() || value.contains('@') {
                format!("sip:{value}")
            } else {
                format!("sip:{value}@{host}")
            }
        }
    }

    fn config() -> RunConfig {
        RunConfig::new("upstream-fake", ClockMode::Virtual, "10.0.0.9:5080")
            .with_header("X-Lane", "upstream-fake")
    }

    #[test]
    fn a_send_carries_its_frozen_headers_its_tier_two_uris_and_the_lane_s_own_headers() {
        let state = RunState::new();
        let bindings = IdentityBindings::new();
        let resolver = Resolver::new(&state, &bindings);
        let msg = MsgSpec {
            method: Some("INVITE".into()),
            ruri: Some(Ref::Positional(PositionalRef {
                pos: "called[0][0]".into(),
                form: Some("trunk-composed".into()),
            })),
            from: Some(Ref::Positional(PositionalRef {
                pos: "caller".into(),
                form: Some("private".into()),
            })),
            headers: vec![Header { name: "P-Orig".into(), value: "sbc.111".into(), class: None }],
            ..MsgSpec::default()
        };
        let rendered = render(
            &msg,
            "step \"s1\"",
            &Context {
                resolver: &resolver,
                config: &config(),
                effects: &StepEffects::default(),
                composer: &TestComposer,
                base_dir: Path::new("."),
                media: &Booking::new("127.0.0.1", 40000),
                leg: "A",
                call_headers: &BTreeMap::new(),
            },
        )
        .expect("the message composes");
        assert_eq!(rendered.ruri.as_deref(), Some("sip:+1999999900004@10.0.0.9:5080"));
        assert_eq!(rendered.from.as_deref(), Some("sip:0009001@lane.invalid"));
        let names: Vec<&str> =
            rendered.template.headers().iter().map(|h| h.name.as_str()).collect();
        assert_eq!(names, ["P-Orig", "X-Lane"], "the lane's own header rides last");
        assert_eq!(rendered.template.method(), Some(&Method::Invite));
    }

    #[test]
    fn a_call_s_own_directive_rides_its_dial_and_outranks_the_run_wide_header() {
        let state = RunState::new();
        let bindings = IdentityBindings::new();
        let resolver = Resolver::new(&state, &bindings);
        let msg = MsgSpec { method: Some("INVITE".into()), ..MsgSpec::default() };
        let call_headers = BTreeMap::from([
            ("X-Api-Call".to_string(), "{\"destination\":\"idle\"}".to_string()),
            ("X-Lane".to_string(), "this-call".to_string()),
        ]);
        let rendered = render(
            &msg,
            "step \"s10\"",
            &Context {
                resolver: &resolver,
                config: &config(),
                effects: &StepEffects::default(),
                composer: &TestComposer,
                base_dir: Path::new("."),
                media: &Booking::new("127.0.0.1", 40000),
                leg: "A",
                call_headers: &call_headers,
            },
        )
        .expect("the message composes");
        let value = |name: &str| {
            rendered
                .template
                .headers()
                .iter()
                .find(|h| h.name == name)
                .map(|h| h.value.clone())
                .unwrap_or_default()
        };
        assert_eq!(value("X-Api-Call"), "{\"destination\":\"idle\"}");
        assert_eq!(value("X-Lane"), "this-call", "the more specific statement wins");
        // And exactly once: a run-wide header the call restated is not stamped twice.
        assert_eq!(rendered.template.headers().iter().filter(|h| h.name == "X-Lane").count(), 1);
    }

    #[test]
    fn an_accessor_inside_a_header_value_resolves_against_run_state() {
        let mut state = RunState::new();
        let leg = state.leg_mut("B");
        leg.call_id = Some("cid-b".into());
        leg.remote_tag = Some("t9".into());
        let bindings = IdentityBindings::new().bind("transferee", "e164", "+33000900006");
        let resolver = Resolver::new(&state, &bindings);
        let msg = MsgSpec {
            method: Some("REFER".into()),
            headers: vec![Header {
                name: "Refer-To".into(),
                value: "<sip:${num:transferee:e164}@h?Replaces=${leg:B.call-id}%3Bto-tag%3D${leg:B.remote-tag}>"
                    .into(),
                class: None,
            }],
            ..MsgSpec::default()
        };
        let rendered = render(
            &msg,
            "step \"s8\"",
            &Context {
                resolver: &resolver,
                config: &config(),
                effects: &StepEffects::default(),
                composer: &TestComposer,
                base_dir: Path::new("."),
                media: &Booking::new("127.0.0.1", 40000),
                leg: "A",
                call_headers: &BTreeMap::new(),
            },
        )
        .expect("the message composes");
        assert_eq!(
            rendered.template.headers()[0].value,
            "<sip:+33000900006@h?Replaces=cid-b%3Bto-tag%3Dt9>"
        );
    }

    #[test]
    fn an_unresolvable_accessor_refuses_the_send_rather_than_emitting_a_hole() {
        let state = RunState::new();
        let bindings = IdentityBindings::new();
        let resolver = Resolver::new(&state, &bindings);
        let msg = MsgSpec {
            method: Some("REFER".into()),
            headers: vec![Header {
                name: "Refer-To".into(),
                value: "<sip:x@h?Replaces=${leg:B.call-id}>".into(),
                class: None,
            }],
            ..MsgSpec::default()
        };
        let error = render(
            &msg,
            "step \"s8\"",
            &Context {
                resolver: &resolver,
                config: &config(),
                effects: &StepEffects::default(),
                composer: &TestComposer,
                base_dir: Path::new("."),
                media: &Booking::new("127.0.0.1", 40000),
                leg: "A",
                call_headers: &BTreeMap::new(),
            },
        )
        .unwrap_err();
        assert!(matches!(error, RenderError::Accessor { .. }), "{error}");
    }

    #[test]
    fn a_body_reference_that_labels_itself_neither_sdp_nor_typed_is_refused() {
        let dir = std::env::temp_dir().join(format!("pivot-render-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("part.bin"), b"\x00\x01").unwrap();
        let unlabelled = Body::Resource(pivot_schema::body::ResourceBody {
            reference: "part.bin".into(),
            rewrite: vec![],
            mode: None,
            content_type: None,
            compare: None,
        });
        assert!(matches!(
            load_body(&unlabelled, &dir, &Booking::new("127.0.0.1", 40000), "A"),
            Err(RenderError::BodyUnlabelled { .. })
        ));
        let typed = Body::Resource(pivot_schema::body::ResourceBody {
            reference: "part.bin".into(),
            rewrite: vec![],
            mode: Some(pivot_schema::body::BodyMode::FrozenBinary),
            content_type: Some("application/EmergencyCallData.eCall.MSD".into()),
            compare: None,
        });
        let (bytes, ct) = load_body(&typed, &dir, &Booking::new("127.0.0.1", 40000), "A").unwrap();
        assert_eq!(bytes, b"\x00\x01");
        assert_eq!(ct.as_deref(), Some("application/EmergencyCallData.eCall.MSD"));
        std::fs::remove_dir_all(&dir).unwrap();
    }

    /// The multipart shape the corpus carries (an INVITE whose part 0 is the
    /// offer and whose part 1 is the deployment's own payload): every part rides
    /// byte-exact under its own type, the SDP part takes the lane's media
    /// address, and the framing states the boundary it used.
    #[test]
    fn a_multipart_body_frames_each_part_under_its_own_type() {
        let dir = std::env::temp_dir().join(format!("pivot-render-mp-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("uac1_0_0.sdp"),
            "v=0\r\nc=IN IP4 1.2.3.4\r\nm=audio 16804 RTP/AVP 8\r\n",
        )
        .unwrap();
        let indata: &[u8] = &[0x77, 0x15, 0x47, 0x00, 0x83, 0x0a];
        std::fs::write(dir.join("uac1_0_1.bin"), indata).unwrap();
        let body = Body::Multipart(pivot_schema::body::MultipartBody {
            multipart: pivot_schema::body::Multipart {
                content_type: "multipart/mixed".into(),
                parts: vec![
                    pivot_schema::body::Part {
                        content_type: "application/sdp".into(),
                        reference: "uac1_0_0.sdp".into(),
                        rewrite: vec!["c=addr".into(), "m=port".into()],
                        mode: None,
                        content_id: None,
                        headers: vec![],
                        cid_linked: vec![],
                    },
                    pivot_schema::body::Part {
                        content_type: "application/vnd.example.indata".into(),
                        reference: "uac1_0_1.bin".into(),
                        rewrite: vec![],
                        mode: Some(pivot_schema::body::BodyMode::FrozenBinary),
                        content_id: Some("<indata@example.invalid>".into()),
                        headers: vec![
                            pivot_schema::body::EntityHeader {
                                name: "Content-Transfer-Encoding".into(),
                                value: "binary".into(),
                            },
                            pivot_schema::body::EntityHeader {
                                name: "Content-Disposition".into(),
                                value: "signal;handling=optional".into(),
                            },
                        ],
                        cid_linked: vec![],
                    },
                ],
            },
        });
        let media = Booking::new("127.0.0.9", 41000);
        let (bytes, ct) = load_body(&body, &dir, &media, "A").unwrap();
        let ct = ct.expect("a multipart body states the type it framed under");
        let boundary = ct.split("boundary=").nth(1).expect("the type names its boundary");
        assert!(ct.starts_with("multipart/mixed;boundary="), "{ct}");
        let text = String::from_utf8_lossy(&bytes).into_owned();
        assert!(text.starts_with(&format!("--{boundary}\r\nContent-Type: application/sdp\r\n\r\n")));
        assert!(text.contains("c=IN IP4 127.0.0.9\r\n"), "the SDP part took the lane's address");
        assert_eq!(media.held("A", 0), Some(41000), "the SDP part booked the leg's first stream");
        assert!(
            text.contains("m=audio 41000 RTP/AVP 8\r\n"),
            "the SDP part took the port the lane booked it:\n{text}"
        );
        assert!(text.contains("Content-Type: application/vnd.example.indata\r\n"));
        // The stored entity block rides verbatim, `Content-ID` first.
        assert!(
            text.contains(
                "Content-Type: application/vnd.example.indata\r\n\
             Content-ID: <indata@example.invalid>\r\n\
             Content-Transfer-Encoding: binary\r\n\
             Content-Disposition: signal;handling=optional\r\n\r\n"
            ),
            "{text}"
        );
        assert!(
            bytes.windows(indata.len()).any(|w| w == indata),
            "the binary part rides byte-exact"
        );
        assert!(text.ends_with(&format!("--{boundary}--\r\n")));
        std::fs::remove_dir_all(&dir).unwrap();
    }

    /// A `cid-linked` part with no `content-id` of its own is REFUSED: the
    /// header referencing it would point at nothing. A document written before
    /// the id was stored fails loudly rather than emitting a stranded link.
    #[test]
    fn a_cid_linked_part_without_a_content_id_refuses_rather_than_stranding_its_header() {
        let body = Body::Multipart(pivot_schema::body::MultipartBody {
            multipart: pivot_schema::body::Multipart {
                content_type: "multipart/mixed".into(),
                parts: vec![pivot_schema::body::Part {
                    content_type: "application/EmergencyCallData.eCall.MSD".into(),
                    reference: "resources/uac1_0_1.bin".into(),
                    rewrite: vec![],
                    mode: Some(pivot_schema::body::BodyMode::FrozenBinary),
                    content_id: None,
                    headers: vec![],
                    cid_linked: vec!["call-info".into()],
                }],
            },
        });
        let error =
            load_body(&body, Path::new("."), &Booking::new("127.0.0.1", 40000), "A").unwrap_err();
        assert!(
            matches!(&error, RenderError::MultipartCidUnstated { headers, .. } if headers == &["call-info"]),
            "{error}"
        );
    }

    /// The same part stating its id EMITS, under that id: `cid-linked` is a
    /// link record, not a refusal.
    #[test]
    fn a_cid_linked_part_stating_its_content_id_emits_under_it() {
        let dir = std::env::temp_dir().join(format!("pivot-render-cid-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(dir.join("msd.bin"), [0x01, 0x02, 0x03]).unwrap();
        let body = Body::Multipart(pivot_schema::body::MultipartBody {
            multipart: pivot_schema::body::Multipart {
                content_type: "multipart/mixed".into(),
                parts: vec![pivot_schema::body::Part {
                    content_type: "application/EmergencyCallData.eCall.MSD".into(),
                    reference: "msd.bin".into(),
                    rewrite: vec![],
                    mode: Some(pivot_schema::body::BodyMode::FrozenBinary),
                    content_id: Some("<msd@example.invalid>".into()),
                    headers: vec![pivot_schema::body::EntityHeader {
                        name: "Content-Transfer-Encoding".into(),
                        value: "binary".into(),
                    }],
                    cid_linked: vec!["call-info".into()],
                }],
            },
        });
        let (bytes, _) = load_body(&body, &dir, &Booking::new("127.0.0.1", 40000), "A").unwrap();
        let text = String::from_utf8_lossy(&bytes).into_owned();
        assert!(text.contains("Content-ID: <msd@example.invalid>\r\n"), "{text}");
        assert!(text.contains("Content-Transfer-Encoding: binary\r\n"), "{text}");
        std::fs::remove_dir_all(&dir).unwrap();
    }

    /// Both tokens, on the body the corpus's ordinary offer is: the address and
    /// the port are the lane's, the `o=` line's address is NOT (it is not a
    /// connection line), and the framing is untouched.
    #[test]
    fn an_sdp_body_takes_the_lane_s_media_address_and_its_booked_port() {
        let sdp = "v=0\r\no=- 1 1 IN IP4 1.2.3.4\r\nc=IN IP4 1.2.3.4\r\nm=audio 5000 RTP/AVP 0\r\n";
        let media = Booking::new("127.0.0.1", 40000);
        let mut stream = 0usize;
        let out = rewrite_sdp(sdp, both(), &media, "A", &mut stream);
        assert_eq!(
            out,
            "v=0\r\no=- 1 1 IN IP4 1.2.3.4\r\nc=IN IP4 127.0.0.1\r\nm=audio 40000 RTP/AVP 0\r\n"
        );
        assert_eq!(media.held("A", 0), Some(40000));
        assert_eq!(stream, 1, "the one active stream took one booking");
    }

    /// The port field is the ONLY thing an `m=` line loses: the media kind, the
    /// `<port>/<count>` pair count and the whole format list ride byte-exact,
    /// and so does every attribute line around them (RFC 4566 §5.14).
    #[test]
    fn a_media_line_keeps_everything_but_its_port_including_a_port_count() {
        let sdp = "v=0\r\n\
                   c=IN IP4 1.2.3.4\r\n\
                   m=audio 5000/2 RTP/AVP 8 101 0\r\n\
                   a=rtpmap:101 telephone-event/8000\r\n\
                   a=fmtp:101 0-15\r\n\
                   a=sendrecv\r\n\
                   m=image 5008 udptl t38\r\n\
                   a=T38FaxVersion:0\r\n";
        let media = Booking::new("127.0.0.1", 40000);
        let mut stream = 0usize;
        let out = rewrite_sdp(sdp, both(), &media, "B", &mut stream);
        assert_eq!(
            out,
            "v=0\r\n\
             c=IN IP4 127.0.0.1\r\n\
             m=audio 40000/2 RTP/AVP 8 101 0\r\n\
             a=rtpmap:101 telephone-event/8000\r\n\
             a=fmtp:101 0-15\r\n\
             a=sendrecv\r\n\
             m=image 40004 udptl t38\r\n\
             a=T38FaxVersion:0\r\n"
        );
        assert_eq!(stream, 2, "the corpus's audio+T.38 offer books a port per live stream");
    }

    /// A port-0 stream is the capture's own rejected/disabled one (RFC 3264
    /// §5.1): it stays zero and does not take a booking, so the stream that
    /// lives beside it books the leg's FIRST port and not its second.
    #[test]
    fn a_rejected_stream_keeps_its_zero_port_and_books_nothing() {
        let sdp = "m=audio 0 RTP/AVP 8\r\nm=image 6000 udptl t38\r\n";
        let media = Booking::new("127.0.0.1", 40000);
        let mut stream = 0usize;
        let out = rewrite_sdp(sdp, both(), &media, "A", &mut stream);
        assert_eq!(out, "m=audio 0 RTP/AVP 8\r\nm=image 40000 udptl t38\r\n");
        assert_eq!(media.held("A", 1), None, "only one stream was ever booked");
    }

    /// The tokens gate independently: a body stating `c=addr` alone keeps the
    /// port the document holds, and one stating `m=port` alone keeps the
    /// address. Nothing is rewritten that the document did not ask for.
    #[test]
    fn each_rewrite_token_gates_only_its_own_lines() {
        let sdp = "c=IN IP4 1.2.3.4\r\nm=audio 5000 RTP/AVP 0\r\n";
        let media = Booking::new("127.0.0.1", 40000);
        let mut stream = 0usize;
        let addr_only = Rewrite { addr: true, port: false };
        assert_eq!(
            rewrite_sdp(sdp, addr_only, &media, "A", &mut stream),
            "c=IN IP4 127.0.0.1\r\nm=audio 5000 RTP/AVP 0\r\n"
        );
        assert_eq!(media.held("A", 0), None, "no token, no booking");
        let port_only = Rewrite { addr: false, port: true };
        assert_eq!(
            rewrite_sdp(sdp, port_only, &media, "A", &mut stream),
            "c=IN IP4 1.2.3.4\r\nm=audio 40000 RTP/AVP 0\r\n"
        );
    }

    /// On a lane without media the booking answers neither token: a body
    /// stating both rides byte for byte, `c=` address and `m=` port as captured,
    /// under the type the tokens declare, and nothing is booked. The same body
    /// on a rebooked lane is still rewritten.
    #[test]
    fn a_verbatim_booking_leaves_a_tokened_body_byte_for_byte() {
        let dir =
            std::env::temp_dir().join(format!("pivot-render-verbatim-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let stored =
            "v=0\r\no=- 1 1 IN IP4 1.2.3.4\r\nc=IN IP4 1.2.3.4\r\nm=audio 5000 RTP/AVP 0\r\n\
                      c=IN IP4 0.0.0.0\r\nm=video 5002/2 RTP/AVP 96\r\n";
        std::fs::write(dir.join("offer.sdp"), stored).unwrap();
        let body = Body::Resource(pivot_schema::body::ResourceBody {
            reference: "offer.sdp".into(),
            rewrite: vec!["c=addr".into(), "m=port".into()],
            mode: None,
            content_type: None,
            compare: None,
        });
        let verbatim = Booking::verbatim();
        let (bytes, ct) = load_body(&body, &dir, &verbatim, "A").unwrap();
        assert_eq!(String::from_utf8_lossy(&bytes), stored, "no line is rewritten");
        assert_eq!(ct.as_deref(), Some("application/sdp"), "the tokens still label the body");
        assert_eq!(verbatim.held("A", 0), None, "and the port book stays empty");

        let rebooked = Booking::new("127.0.0.1", 40000);
        let (bytes, _) = load_body(&body, &dir, &rebooked, "A").unwrap();
        assert_eq!(
            String::from_utf8_lossy(&bytes),
            "v=0\r\no=- 1 1 IN IP4 1.2.3.4\r\nc=IN IP4 127.0.0.1\r\nm=audio 40000 RTP/AVP 0\r\n\
             c=IN IP4 127.0.0.1\r\nm=video 40002/2 RTP/AVP 96\r\n",
            "a rebooked lane still rewrites"
        );
        assert_eq!(rebooked.held("A", 1), Some(40002));
        std::fs::remove_dir_all(&dir).unwrap();
    }

    /// A body stating NO rewrite token is not SDP at all: it rides byte-exact
    /// under its stored type, ports included.
    #[test]
    fn a_body_stating_no_rewrite_token_keeps_its_stored_port() {
        let dir = std::env::temp_dir().join(format!("pivot-render-frozen-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let stored = "v=0\r\nc=IN IP4 1.2.3.4\r\nm=audio 5000 RTP/AVP 0\r\n";
        std::fs::write(dir.join("frozen.sdp"), stored).unwrap();
        let body = Body::Resource(pivot_schema::body::ResourceBody {
            reference: "frozen.sdp".into(),
            rewrite: vec![],
            mode: Some(pivot_schema::body::BodyMode::Frozen),
            content_type: Some("application/sdp".into()),
            compare: None,
        });
        let media = Booking::new("127.0.0.1", 40000);
        let (bytes, ct) = load_body(&body, &dir, &media, "A").unwrap();
        assert_eq!(String::from_utf8_lossy(&bytes), stored, "a frozen body is not rewritten");
        assert_eq!(ct.as_deref(), Some("application/sdp"));
        assert_eq!(media.held("A", 0), None, "and books nothing");
        std::fs::remove_dir_all(&dir).unwrap();
    }

    /// What every corpus-generated SDP body states.
    fn both() -> Rewrite {
        Rewrite::of(&["c=addr".to_string(), "m=port".to_string()])
    }
}
