apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: vm
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    jsonData:
      timeInterval: 15s
      httpMethod: POST

  - name: VictoriaLogs
    uid: vl
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
    jsonData:
      maxLines: 1000

  - name: VictoriaTraces
    uid: vt
    type: jaeger
    access: proxy
    url: http://victoria-traces:10428/select/jaeger
    jsonData:
      nodeGraph:
        enabled: true
