//! PROPERTY TEST — eventual convergence (the goal-1 invariant).
//!
//! After a randomized-ish sequence of puts / deletes / partitions / heals on a
//! 2-node cluster, then quiescence (advance enough for all in-flight frames to
//! land), assert EVERY reachable node's view of each call equals the latest
//! `call_gen` (the goal-1 convergence invariant).
//!
//! ## Determinism (CLAUDE.md + workflow rules: no `Math.random` / `Date::now`)
//! The operation sequence is generated by a fixed-seed hand-rolled LCG — NOT
//! `rand` / `Date::now`. Each seed yields a fixed sequence, so the test is fully
//! reproducible. We sweep a handful of seeds (each its own paused-clock run) to
//! cover a spread of interleavings while staying deterministic. The model is a
//! per-call expected `(call_gen → body)`; quiescence convergence is checked
//! against it. Crash/reboot is exercised in the dedicated scenarios; here we
//! keep both nodes alive and vary mutations + partitions so the invariant is a
//! clean function of LWW + delivery (no incarnation churn to confound it).
//!
//! ## callRefs are unique — deletes are final (resurrection tombstone)
//! The store's Model Y resurrection tombstone (`put_call` delete-wins guard,
//! `RESURRECTION_TOMBSTONE_MS`) silently rejects a Put for a ref deleted within
//! the tombstone window: production callRefs are unique, so a deleted ref never
//! legitimately comes back, and a late reverse-flush must not re-create a
//! discharged call. The driver honours that contract by bumping a per-key
//! *epoch* after every delete — a "recreated" call is a NEW unique callRef, not
//! a resurrection of the deleted one. Live-ref updates still collide on the
//! small key space, so LWW stays exercised.

use std::collections::HashMap;
use std::time::Duration;

use ha_harness::{backup_is, cref, HaCluster, PartitionRole};

const PRI: PartitionRole = PartitionRole::Primary;
const BAK: PartitionRole = PartitionRole::Backup;

/// A tiny deterministic LCG (Numerical Recipes constants). No global RNG, no
/// wall clock — the seed fully determines the stream.
struct Lcg(u64);
impl Lcg {
    fn next_u32(&mut self) -> u32 {
        self.0 = self.0.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        (self.0 >> 33) as u32
    }
    fn below(&mut self, n: u32) -> u32 {
        self.next_u32() % n
    }
}

/// One driven step over a 2-node A/B cluster. `latest` tracks the highest
/// (call_gen, body, deleted) the model expects per callRef so the final
/// convergence check knows the winner.
async fn run_sequence(seed: u64) {
    let mut cl = HaCluster::new(&["A", "B"]).await;
    cl.advance(Duration::from_millis(200)).await;

    // Model: callRef → (highest_gen, body_or_none_if_deleted).
    let mut latest: HashMap<String, (i64, Option<Vec<u8>>)> = HashMap::new();
    // Monotonic per-call gen so each authoritative mutation strictly increases.
    let mut gen_of: HashMap<String, i64> = HashMap::new();
    let mut rng = Lcg(seed);
    let mut partitioned = false;

    // A owns calls "A|k|.."; B owns "B|k|..". Each picks its own backup (the
    // other node) and forward-replicates. Keep a small key space so updates +
    // deletes collide and LWW is actually exercised.
    let keys = 4u32;
    // Per-A-key delete epoch: a delete retires the current callRef forever
    // (resurrection-tombstone contract, see module doc); the next put on the
    // same key targets a fresh unique ref.
    let mut epoch = [0u32; 4];
    let a_id = |k: u32, epoch: &[u32; 4]| format!("{k}e{}", epoch[k as usize]);

    for _ in 0..40 {
        match rng.below(10) {
            // put/update A-owned call (forward A→B).
            0..=3 => {
                let k = rng.below(keys);
                let c = cref("A", &a_id(k, &epoch));
                let g = gen_of.entry(c.clone()).or_insert(0);
                *g += 1;
                let body = format!("A{k}@g{}", *g).into_bytes();
                cl.put("A", &c, body.clone(), *g, 0, &backup_is("B")).await;
                latest.insert(c, (*g, Some(body)));
            }
            // put/update B-owned call (forward B→A).
            4..=6 => {
                let k = rng.below(keys);
                let c = cref("B", &k.to_string());
                let g = gen_of.entry(c.clone()).or_insert(0);
                *g += 1;
                let body = format!("B{k}@g{}", *g).into_bytes();
                cl.put("B", &c, body.clone(), *g, 0, &backup_is("A")).await;
                latest.insert(c, (*g, Some(body)));
            }
            // delete an A-owned call (final for that ref: bump the key's epoch
            // so a later put on the same key is a new call, not a resurrection).
            7 => {
                let k = rng.below(keys);
                let c = cref("A", &a_id(k, &epoch));
                if gen_of.contains_key(&c) {
                    let g = gen_of.get_mut(&c).unwrap();
                    *g += 1;
                    cl.delete("A", &c, &backup_is("B")).await;
                    latest.insert(c, (*g, None));
                    epoch[k as usize] += 1;
                }
            }
            // toggle partition / heal between A and B.
            8 => {
                if partitioned {
                    cl.heal("A", "B");
                    partitioned = false;
                } else {
                    cl.partition("A", "B");
                    partitioned = true;
                }
            }
            // a small advance to let frames flow mid-sequence.
            _ => {
                cl.advance(Duration::from_millis(100)).await;
            }
        }
        // A short advance after each op so the pipeline makes progress.
        cl.advance(Duration::from_millis(100)).await;
    }

    // QUIESCE: make sure no partition lingers, then advance generously so every
    // retained-W tail / reconnect drains and both nodes converge.
    if partitioned {
        cl.heal("A", "B");
    }
    cl.advance(Duration::from_secs(5)).await;

    // INVARIANT: for every call the model touched, BOTH nodes' views equal the
    // latest call_gen's body (or absence). A-owned calls live as pri:A on A and
    // bak:A on B; B-owned calls live as pri:B on B and bak:B on A.
    for (call_ref, (want_gen, want_body)) in &latest {
        let owner = &call_ref[..1]; // "A" or "B".
        let (primary_role, backup_role) = (PRI, BAK);
        let (on_owner, on_other, owner_node, other_node) = if owner == "A" {
            (primary_role, backup_role, "A", "B")
        } else {
            (primary_role, backup_role, "B", "A")
        };

        let owner_view = cl.node(owner_node).get(on_owner, owner, call_ref).await;
        let other_view = cl.node(other_node).get(on_other, owner, call_ref).await;

        match want_body {
            Some(body) => {
                assert_eq!(
                    owner_view.as_deref(),
                    Some(&body[..]),
                    "seed {seed}: owner {owner_node} view of {call_ref} != latest gen {want_gen}"
                );
                assert_eq!(
                    other_view.as_deref(),
                    Some(&body[..]),
                    "seed {seed}: peer {other_node} view of {call_ref} != latest gen {want_gen}"
                );
                // Both nodes agree on the content version too.
                assert_eq!(
                    cl.node(owner_node).call_gen(on_owner, owner, call_ref),
                    Some(*want_gen),
                    "seed {seed}: owner call_gen for {call_ref}"
                );
            }
            None => {
                assert!(
                    owner_view.is_none(),
                    "seed {seed}: owner {owner_node} still has deleted {call_ref}"
                );
                assert!(
                    other_view.is_none(),
                    "seed {seed}: peer {other_node} still has deleted {call_ref}"
                );
            }
        }
    }
}

#[tokio::test(start_paused = true)]
async fn eventual_convergence_seed_1() {
    run_sequence(1).await;
}

#[tokio::test(start_paused = true)]
async fn eventual_convergence_seed_7() {
    run_sequence(7).await;
}

#[tokio::test(start_paused = true)]
async fn eventual_convergence_seed_42() {
    run_sequence(42).await;
}

#[tokio::test(start_paused = true)]
async fn eventual_convergence_seed_1337() {
    run_sequence(1337).await;
}

#[tokio::test(start_paused = true)]
async fn eventual_convergence_seed_99991() {
    run_sequence(99991).await;
}
