//! `MessageTemplate` — a captured SIP message prepared for near-verbatim
//! replay. The stack regenerates the dialog-critical (tier-1) fields from live
//! dialog/transaction state and emits every other header byte-for-byte.
//!
//! A template splits its headers into two classes ([`HeaderClass`]):
//!
//! - **Regenerated** — the fields the stack MUST own for the replayed message to
//!   be a valid, routable member of a live dialog: `Via` (+branch), `From`/`To`
//!   (tags), `Call-ID`, `CSeq` (number), `Max-Forwards`, `Content-Length`,
//!   `Contact` (host:port) and the `Route`/`Record-Route` set. Their stored
//!   values are dropped on emission; the generator fills them.
//! - **Frozen** — every other header, emitted byte-for-byte: value bytes,
//!   header-name casing, and duplicate-header layout all preserved. `Content-Type`
//!   is deliberately frozen (a captured unusual media type must survive), even
//!   though `Content-Length` is regenerated.
//!
//! # v1 emission limitation
//!
//! Header ORDER is canonical in v1: the stack emits its regenerated block first,
//! then the frozen headers in their captured relative order. [`EmitOpts`] carries
//! `preserve_order` so a caller can request original absolute ordering, but v1
//! honours it only for casing + duplicate-header layout (always preserved for
//! frozen headers regardless) — it does NOT yet restore the original interleaving
//! of frozen and regenerated headers. The flag is threaded for API stability.

use crate::method::Method;
use crate::types::{SipHeader, SipMessage};

/// The tier-1 headers the stack regenerates from live dialog/transaction state.
/// Everything else is [`HeaderClass::Frozen`]. Note this is NOT the relay
/// "structural" set: `Content-Type` is absent here (frozen), while
/// `Content-Length` (serializer-owned) is present.
const REGENERATED_HEADERS: &[&str] = &[
    "via",
    "from",
    "to",
    "call-id",
    "cseq",
    "max-forwards",
    "content-length",
    "contact",
    "route",
    "record-route",
];

/// How the stack treats one templated header when the message is emitted.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HeaderClass {
    /// Regenerated by the stack from live dialog/transaction state; the
    /// template's stored value is dropped.
    Regenerated,
    /// Emitted byte-for-byte (value, name casing, duplicate layout preserved).
    Frozen,
}

impl HeaderClass {
    /// The default classification of a header by name (case-insensitive): a
    /// tier-1 dialog-critical name is [`Regenerated`](HeaderClass::Regenerated),
    /// everything else is [`Frozen`](HeaderClass::Frozen).
    pub fn of(name: &str) -> Self {
        let lower = name.to_ascii_lowercase();
        if REGENERATED_HEADERS.contains(&lower.as_str()) {
            HeaderClass::Regenerated
        } else {
            HeaderClass::Frozen
        }
    }
}

/// One header of a [`MessageTemplate`]: its original wire name (casing
/// preserved), its value, and how the stack treats it on emission.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TemplateHeader {
    pub name: String,
    pub value: String,
    pub class: HeaderClass,
}

impl TemplateHeader {
    /// A header classified by its name (the default tier model).
    pub fn classified(name: impl Into<String>, value: impl Into<String>) -> Self {
        let name = name.into();
        let class = HeaderClass::of(&name);
        TemplateHeader { name, value: value.into(), class }
    }

    /// A header forced [`Frozen`](HeaderClass::Frozen) regardless of name.
    pub fn frozen(name: impl Into<String>, value: impl Into<String>) -> Self {
        TemplateHeader { name: name.into(), value: value.into(), class: HeaderClass::Frozen }
    }

    /// A header forced [`Regenerated`](HeaderClass::Regenerated) regardless of name.
    pub fn regenerated(name: impl Into<String>, value: impl Into<String>) -> Self {
        TemplateHeader { name: name.into(), value: value.into(), class: HeaderClass::Regenerated }
    }
}

/// The start line a [`MessageTemplate`] reproduces.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TemplateStart {
    /// A request of this method (the Request-URI is a tier-1 regenerated field,
    /// so it is not stored on the template).
    Request(Method),
    /// A response of this status code / reason phrase.
    Response { status: u16, reason: String },
}

/// A captured SIP message prepared for near-verbatim replay. Holds the start
/// line, an ordered list of classified headers (wire casing + duplicate layout
/// preserved), and the raw body bytes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MessageTemplate {
    start: TemplateStart,
    headers: Vec<TemplateHeader>,
    body: Vec<u8>,
}

impl MessageTemplate {
    /// A request template with explicitly classified headers.
    pub fn request(method: Method, headers: Vec<TemplateHeader>, body: Vec<u8>) -> Self {
        MessageTemplate { start: TemplateStart::Request(method), headers, body }
    }

    /// A response template with explicitly classified headers.
    pub fn response(
        status: u16,
        reason: impl Into<String>,
        headers: Vec<TemplateHeader>,
        body: Vec<u8>,
    ) -> Self {
        MessageTemplate {
            start: TemplateStart::Response { status, reason: reason.into() },
            headers,
            body,
        }
    }

    /// Build a template from a parsed message, classifying every header by name
    /// (the default tier model). The header list keeps the message's wire order,
    /// casing, and duplicate-header layout.
    pub fn from_message(msg: &SipMessage) -> Self {
        let headers = msg
            .headers()
            .iter()
            .map(|h| TemplateHeader::classified(h.name.clone(), h.value.clone()))
            .collect();
        let (start, body) = match msg {
            SipMessage::Request(r) => (TemplateStart::Request(r.method.clone()), r.body.clone()),
            SipMessage::Response(r) => (
                TemplateStart::Response { status: r.status, reason: r.reason.clone() },
                r.body.clone(),
            ),
        };
        MessageTemplate { start, headers, body }
    }

    /// The start line this template reproduces.
    pub fn start(&self) -> &TemplateStart {
        &self.start
    }

    /// The request method, if this is a request template.
    pub fn method(&self) -> Option<&Method> {
        match &self.start {
            TemplateStart::Request(m) => Some(m),
            TemplateStart::Response { .. } => None,
        }
    }

    /// The `(status, reason)`, if this is a response template.
    pub fn status(&self) -> Option<(u16, &str)> {
        match &self.start {
            TemplateStart::Response { status, reason } => Some((*status, reason.as_str())),
            TemplateStart::Request(_) => None,
        }
    }

    /// All classified headers in captured order.
    pub fn headers(&self) -> &[TemplateHeader] {
        &self.headers
    }

    /// The frozen headers as ready-to-emit [`SipHeader`]s, in captured order,
    /// casing and duplicate layout preserved — the `extra_headers` a stack
    /// generator appends verbatim after its regenerated block.
    pub fn frozen_headers(&self) -> Vec<SipHeader> {
        self.headers
            .iter()
            .filter(|h| h.class == HeaderClass::Frozen)
            .map(|h| SipHeader { name: h.name.clone(), value: h.value.clone() })
            .collect()
    }

    /// The raw body bytes (opaque — SDP, multipart, or any captured payload).
    pub fn body(&self) -> &[u8] {
        &self.body
    }
}

/// Options controlling template emission.
///
/// `preserve_order` requests that the original absolute header ORDER be
/// reproduced. See the module doc: v1 honours it only for casing +
/// duplicate-header layout (always preserved for frozen headers), and does NOT
/// yet restore the original interleaving of frozen and regenerated headers.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct EmitOpts {
    pub preserve_order: bool,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::custom::CustomParser;
    use crate::parser::SipParser;

    fn parse(raw: &[u8]) -> SipMessage {
        CustomParser::new().parse(raw).expect("well-formed")
    }

    #[test]
    fn classifies_tier1_vs_frozen_by_name() {
        assert_eq!(HeaderClass::of("Via"), HeaderClass::Regenerated);
        assert_eq!(HeaderClass::of("CALL-ID"), HeaderClass::Regenerated);
        assert_eq!(HeaderClass::of("cseq"), HeaderClass::Regenerated);
        assert_eq!(HeaderClass::of("Content-Length"), HeaderClass::Regenerated);
        assert_eq!(HeaderClass::of("Record-Route"), HeaderClass::Regenerated);
        // Content-Type is FROZEN even though Content-Length is regenerated.
        assert_eq!(HeaderClass::of("Content-Type"), HeaderClass::Frozen);
        assert_eq!(HeaderClass::of("P-Asserted-Identity"), HeaderClass::Frozen);
        assert_eq!(HeaderClass::of("X-Custom"), HeaderClass::Frozen);
    }

    #[test]
    fn from_message_preserves_casing_order_and_duplicates() {
        let raw = b"INVITE sip:bob@example.com SIP/2.0\r\n\
Via: SIP/2.0/UDP 10.0.0.1:5060;branch=z9hG4bK-abc\r\n\
Max-Forwards: 70\r\n\
From: <sip:alice@example.com>;tag=at\r\n\
To: <sip:bob@example.com>\r\n\
Call-ID: c-1@10.0.0.1\r\n\
CSeq: 1 INVITE\r\n\
Contact: <sip:alice@10.0.0.1:5060>\r\n\
p-AsSeRtEd-IdEnTiTy: <sip:+15550001@example.com>\r\n\
X-Dup: one\r\n\
X-Dup: two\r\n\
Content-Type: application/sdp\r\n\
Content-Length: 0\r\n\r\n";
        let msg = parse(raw);
        let tmpl = MessageTemplate::from_message(&msg);
        assert_eq!(tmpl.method(), Some(&Method::Invite));

        let frozen = tmpl.frozen_headers();
        // Tier-1 headers (Via/From/To/Call-ID/CSeq/Max-Forwards/Contact/
        // Content-Length) are excluded; Content-Type + the customs remain.
        let names: Vec<&str> = frozen.iter().map(|h| h.name.as_str()).collect();
        assert_eq!(names, vec!["p-AsSeRtEd-IdEnTiTy", "X-Dup", "X-Dup", "Content-Type"]);
        // Casing preserved verbatim.
        assert_eq!(frozen[0].name, "p-AsSeRtEd-IdEnTiTy");
        assert_eq!(frozen[0].value, "<sip:+15550001@example.com>");
        // Both duplicate rows preserved in order.
        assert_eq!(frozen[1].value, "one");
        assert_eq!(frozen[2].value, "two");
    }

    #[test]
    fn response_template_carries_status_and_reason() {
        let tmpl = MessageTemplate::response(
            486,
            "Busy Here",
            vec![TemplateHeader::frozen("Retry-After", "30")],
            Vec::new(),
        );
        assert_eq!(tmpl.status(), Some((486, "Busy Here")));
        assert_eq!(tmpl.method(), None);
        assert_eq!(tmpl.frozen_headers().len(), 1);
    }
}
