//! `MessageTemplate` — a captured SIP message prepared for near-verbatim
//! replay. The stack regenerates the dialog-critical (tier-1) fields from live
//! dialog/transaction state and emits every other header byte-for-byte.
//!
//! A template splits its headers into two classes ([`HeaderClass`]):
//!
//! - **Regenerated** — the fields the stack MUST own for the replayed message to
//!   be a valid, routable member of a live dialog: `Via` (+branch), `From`/`To`
//!   (tags), `Call-ID`, `CSeq` (number), `Max-Forwards`, `Content-Length`,
//!   `Contact` (host:port) and the `Route`/`Record-Route` set. Their stored
//!   values are dropped on emission; the generator fills them.
//! - **Frozen** — every other header, emitted byte-for-byte: value bytes,
//!   header-name casing, and duplicate-header layout all preserved. `Content-Type`
//!   is deliberately frozen (a captured unusual media type must survive), even
//!   though `Content-Length` is regenerated.
//!
//! # Fidelity is relative to the PARSED value
//!
//! "Byte-for-byte" preservation is of the *parsed* header value, not the raw
//! capture bytes: a folded value (RFC 3261 §7.3.1 `\r\n`+WSP line continuation)
//! is emitted unfolded, and surrounding optional whitespace is trimmed — exactly
//! the normalization [`SipHeader`] already applies. This is stable across the
//! extract → replay → re-extract loop but is not the original wire framing.
//!
//! # Compact header-name fidelity, and the ONE canonicalization source
//!
//! A message captured with RFC 3261 §7.3.3 compact names (`v` Via, `f` From,
//! `t` To, `i` Call-ID, `m` Contact, `c` Content-Type, …) replays with those
//! compact names — for frozen headers AND for the tier-1 headers the stack
//! regenerates. The parser canonicalizes `SipHeader.name` (so all matching stays
//! canonical), and [`from_message`](MessageTemplate::from_message) recovers the
//! captured wire form from the exact bytes. Templates from captures MUST be built
//! via `from_message` over wire bytes; the raw-line constructors are for tests.
//! Header-name classification / canonicalization has ONE source of truth — the
//! parser's compact-form table (`HeaderClass::of` and the presence probes both
//! expand through it). v1 boundary: a REGENERATED header captured in mixed
//! name-forms across duplicate rows (`Via:` + `v:`) replays under one compact
//! form — see [`MessageTemplate::regenerated_name_forms`].
//!
//! # Automatics are not template-overridable in v1
//!
//! Stack automatics and dedicated primitives — `100 Trying`, the `ACK` to a
//! final, `CANCEL`, and the `487` a CANCEL triggers — cannot carry template
//! headers in v1: they are emitted by the stack / their own primitives, which
//! take no template. A captured ACK's or CANCEL's frozen-header quirks are not
//! replayable yet.
//!
//! # v1 emission limitation
//!
//! Header ORDER is canonical in v1: the stack emits its regenerated block first,
//! then the frozen headers in their captured relative order. [`EmitOpts`] carries
//! `preserve_order` so a caller can request original absolute ordering, but v1
//! honours it only for casing + duplicate-header layout (always preserved for
//! frozen headers regardless) — it does NOT yet restore the original interleaving
//! of frozen and regenerated headers. The flag is threaded for API stability.

use crate::method::Method;
use crate::types::{SipHeader, SipMessage};

/// The tier-1 headers the stack regenerates from live dialog/transaction state.
/// Everything else is [`HeaderClass::Frozen`]. Note this is NOT the relay
/// "structural" set: `Content-Type` is absent here (frozen), while
/// `Content-Length` (serializer-owned) is present.
const REGENERATED_HEADERS: &[&str] = &[
    "via",
    "from",
    "to",
    "call-id",
    "cseq",
    "max-forwards",
    "content-length",
    "contact",
    "route",
    "record-route",
];

/// How the stack treats one templated header when the message is emitted.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HeaderClass {
    /// Regenerated by the stack from live dialog/transaction state; the
    /// template's stored value is dropped.
    Regenerated,
    /// Emitted byte-for-byte (value, name casing, duplicate layout preserved).
    Frozen,
}

impl HeaderClass {
    /// The default classification of a header by name (case-insensitive): a
    /// tier-1 dialog-critical name is [`Regenerated`](HeaderClass::Regenerated),
    /// everything else is [`Frozen`](HeaderClass::Frozen). RFC 3261 §7.3.3
    /// compact forms are expanded first, so `"v"` classifies as `Via` (else a
    /// templated compact tier-1 header would freeze and duplicate on the wire).
    pub fn of(name: &str) -> Self {
        let expanded = crate::parser::custom::compact_forms::expand_compact_form(name);
        if REGENERATED_HEADERS.contains(&expanded.to_ascii_lowercase().as_str()) {
            HeaderClass::Regenerated
        } else {
            HeaderClass::Frozen
        }
    }
}

/// One header of a [`MessageTemplate`]: its **canonical** name (compact forms
/// expanded, casing preserved), its value, how the stack treats it on emission,
/// and the as-wire name-form to emit under when the capture used a compact form
/// (`wire_name = Some("v")` for a `v:` Via; `None` when the wire name already
/// equals the canonical name).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TemplateHeader {
    pub name: String,
    pub value: String,
    pub class: HeaderClass,
    /// The captured wire name-form when it differs from `name` (a §7.3.3 compact
    /// form). `None` for the raw-line constructors and for headers captured under
    /// their canonical name. Attribution assumes the message's `headers` and
    /// `raw` are the parse-time originals (the parse-then-template contract): a
    /// post-parse header mutation could misalign this against the raw bytes.
    pub wire_name: Option<String>,
}

impl TemplateHeader {
    /// A header classified by its name (the default tier model). No wire-form
    /// override — for the raw-line (test) constructors; captures set the wire
    /// form via [`MessageTemplate::from_message`].
    pub fn classified(name: impl Into<String>, value: impl Into<String>) -> Self {
        let name = name.into();
        let class = HeaderClass::of(&name);
        TemplateHeader { name, value: value.into(), class, wire_name: None }
    }

    /// A header forced [`Frozen`](HeaderClass::Frozen) regardless of name.
    pub fn frozen(name: impl Into<String>, value: impl Into<String>) -> Self {
        TemplateHeader {
            name: name.into(),
            value: value.into(),
            class: HeaderClass::Frozen,
            wire_name: None,
        }
    }

    /// A header forced [`Regenerated`](HeaderClass::Regenerated) regardless of name.
    pub fn regenerated(name: impl Into<String>, value: impl Into<String>) -> Self {
        TemplateHeader {
            name: name.into(),
            value: value.into(),
            class: HeaderClass::Regenerated,
            wire_name: None,
        }
    }

    /// The name-form to EMIT under: the captured wire form if present, else the
    /// canonical name.
    fn emit_name(&self) -> &str {
        self.wire_name.as_deref().unwrap_or(&self.name)
    }
}

/// The start line a [`MessageTemplate`] reproduces.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TemplateStart {
    /// A request of this method (the Request-URI is a tier-1 regenerated field,
    /// so it is not stored on the template).
    Request(Method),
    /// A response of this status code / reason phrase.
    Response { status: u16, reason: String },
}

/// A captured SIP message prepared for near-verbatim replay. Holds the start
/// line, an ordered list of classified headers (wire casing + duplicate layout
/// preserved), and the raw body bytes. A template describes a message a UA
/// deliberately emits; the stack automatics and dedicated primitives (`100`,
/// `ACK`, `CANCEL`, `487`) take no template in v1 (module doc).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MessageTemplate {
    start: TemplateStart,
    headers: Vec<TemplateHeader>,
    body: Vec<u8>,
}

impl MessageTemplate {
    /// A request template with explicitly classified headers.
    pub fn request(method: Method, headers: Vec<TemplateHeader>, body: Vec<u8>) -> Self {
        MessageTemplate { start: TemplateStart::Request(method), headers, body }
    }

    /// A response template with explicitly classified headers.
    pub fn response(
        status: u16,
        reason: impl Into<String>,
        headers: Vec<TemplateHeader>,
        body: Vec<u8>,
    ) -> Self {
        MessageTemplate {
            start: TemplateStart::Response { status, reason: reason.into() },
            headers,
            body,
        }
    }

    /// Build a template from a parsed message, classifying every header by
    /// (canonical) name and recovering each header's captured **wire** name-form
    /// from the message's original bytes — so a §7.3.3 compact name (`v`, `f`,
    /// `t`, `i`, `m`, `c`, …) replays compact. The header list keeps the message's
    /// wire order, casing, and duplicate-header layout.
    ///
    /// This is THE capture path: it reads the exact wire bytes (`SipRequest.raw`
    /// / `SipResponse.raw`). A message with no retained raw bytes (one the stack
    /// generated rather than parsed) yields canonical names only. The raw-line
    /// [`request`](Self::request) / [`response`](Self::response) constructors are
    /// for tests.
    ///
    /// Scans under the default parser limits. If the message was parsed under
    /// laxer limits, the re-scan may fail and every header falls back to its
    /// canonical name (compact fidelity lost, not incorrect); use
    /// [`from_message_with_limits`](Self::from_message_with_limits) with the
    /// original limits to avoid that.
    pub fn from_message(msg: &SipMessage) -> Self {
        Self::from_message_with_limits(msg, &crate::parser::SipParserLimits::default())
    }

    /// [`from_message`](Self::from_message) scanning the wire name-forms under an
    /// explicit parser-limits set — pass the limits the message was PARSED under
    /// so the re-scan of its raw bytes reproduces the same header split. A
    /// mismatch (scanning stricter than the message was parsed) makes the scan
    /// fail and every header fall back to its canonical name (no compact
    /// fidelity, never wrong values).
    pub fn from_message_with_limits(
        msg: &SipMessage,
        limits: &crate::parser::SipParserLimits,
    ) -> Self {
        let (start, body, raw) = match msg {
            SipMessage::Request(r) => {
                (TemplateStart::Request(r.method.clone()), r.body.clone(), &r.raw)
            }
            SipMessage::Response(r) => (
                TemplateStart::Response { status: r.status, reason: r.reason.clone() },
                r.body.clone(),
                &r.raw,
            ),
        };
        // Recover per-header wire names from the exact capture bytes; align 1:1
        // with the parsed header list, else fall back to canonical (no compact).
        let wire_names = if raw.is_empty() {
            Vec::new()
        } else {
            crate::parser::custom::headers::scan_header_name_forms(raw, limits)
        };
        let parsed = msg.headers();
        let aligned = wire_names.len() == parsed.len();
        let headers = parsed
            .iter()
            .enumerate()
            .map(|(i, h)| {
                let wire_name = if aligned && wire_names[i] != h.name {
                    Some(wire_names[i].clone())
                } else {
                    None
                };
                TemplateHeader {
                    name: h.name.clone(),
                    value: h.value.clone(),
                    class: HeaderClass::of(&h.name),
                    wire_name,
                }
            })
            .collect();
        MessageTemplate { start, headers, body }
    }

    /// The start line this template reproduces.
    pub fn start(&self) -> &TemplateStart {
        &self.start
    }

    /// The request method, if this is a request template.
    pub fn method(&self) -> Option<&Method> {
        match &self.start {
            TemplateStart::Request(m) => Some(m),
            TemplateStart::Response { .. } => None,
        }
    }

    /// The `(status, reason)`, if this is a response template.
    pub fn status(&self) -> Option<(u16, &str)> {
        match &self.start {
            TemplateStart::Response { status, reason } => Some((*status, reason.as_str())),
            TemplateStart::Request(_) => None,
        }
    }

    /// All classified headers in captured order.
    pub fn headers(&self) -> &[TemplateHeader] {
        &self.headers
    }

    /// The frozen headers as ready-to-emit [`SipHeader`]s, in captured order,
    /// casing, duplicate layout, and **wire name-form** preserved (a compact
    /// `c:` Content-Type emits `c:`) — the `extra_headers` a stack generator
    /// appends verbatim after its regenerated block.
    pub fn frozen_headers(&self) -> Vec<SipHeader> {
        self.headers
            .iter()
            .filter(|h| h.class == HeaderClass::Frozen)
            .map(|h| SipHeader { name: h.emit_name().to_string(), value: h.value.clone() })
            .collect()
    }

    /// The captured compact name-forms of the REGENERATED (tier-1) headers the
    /// stack itself emits — `(canonical, wire)` pairs such as `("Via", "v")`,
    /// `("From", "f")`, `("To", "t")`, `("Call-ID", "i")`, `("Contact", "m")`.
    /// The emission path applies these (via [`apply_name_forms`]) so a capture
    /// that used compact names replays compact on the stack-owned lines too.
    ///
    /// `Content-Length` is deliberately excluded: its name-form is serializer-
    /// owned (the serializer enforces the value by the canonical name), so it
    /// always emits under the canonical name.
    ///
    /// v1 boundary — mixed-form duplicate rows collapse: the map is keyed by
    /// canonical name and [`apply_name_forms`] rewrites EVERY row of a matching
    /// header, so a regenerated header captured in mixed forms across duplicate
    /// rows (`Via:` + `v:`) replays entirely under the one compact form. This is
    /// intrinsic to regenerating these headers (the stack emits its own count,
    /// not the capture's rows) and is invisible to the parsed-value repro differ
    /// (which compares canonicalized values). Per-row name-forms are deferred.
    pub fn regenerated_name_forms(&self) -> Vec<(String, String)> {
        self.headers
            .iter()
            .filter(|h| h.class == HeaderClass::Regenerated)
            .filter_map(|h| h.wire_name.as_ref().map(|w| (h.name.clone(), w.clone())))
            .filter(|(canon, _)| !canon.eq_ignore_ascii_case("content-length"))
            .collect()
    }

    /// The Regenerated remote-target headers (`Contact`/`Route`/`Record-Route`)
    /// whose host:port is stack-owned (routing-critical) but whose user part +
    /// ALL parameters are captured — `(canonical_lowercase_name, captured_value)`.
    /// The emission path rewrites the generated header's host:port onto the
    /// captured value (via [`apply_remote_target_emits`]), so a param'd/user'd
    /// Contact round-trips. A remote-target header explicitly FROZEN rides
    /// [`frozen_headers`](Self::frozen_headers) verbatim instead (host:port kept).
    pub fn remote_target_emits(&self) -> Vec<(String, String)> {
        self.headers
            .iter()
            .filter(|h| {
                h.class == HeaderClass::Regenerated && crate::remote_target::is_remote_target(&h.name)
            })
            .map(|h| (crate::remote_target::canonical(&h.name), h.value.clone()))
            .collect()
    }

    /// The raw body bytes (opaque — SDP, multipart, or any captured payload).
    pub fn body(&self) -> &[u8] {
        &self.body
    }
}

/// Options controlling template emission.
///
/// `preserve_order` requests that the original absolute header ORDER be
/// reproduced. See the module doc: v1 honours it only for casing +
/// duplicate-header layout (always preserved for frozen headers), and does NOT
/// yet restore the original interleaving of frozen and regenerated headers.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct EmitOpts {
    pub preserve_order: bool,
}

/// Rewrite each header whose canonical name matches a `(canonical, wire)` entry
/// to the mapped wire name-form (compact-name replay of the stack-regenerated
/// headers). Non-matching headers pass through unchanged; an empty map is the
/// identity (today's full names). Values are untouched. Used by the template
/// emission path to write `v:`/`f:`/… for a capture that used compact names.
pub fn apply_name_forms(headers: &[SipHeader], forms: &[(String, String)]) -> Vec<SipHeader> {
    if forms.is_empty() {
        return headers.to_vec();
    }
    headers
        .iter()
        .map(|h| {
            let wire = forms
                .iter()
                .find(|(canon, _)| h.name.eq_ignore_ascii_case(canon))
                .map(|(_, w)| w.clone());
            SipHeader { name: wire.unwrap_or_else(|| h.name.clone()), value: h.value.clone() }
        })
        .collect()
}

/// Rewrite each generated remote-target header to carry the CAPTURED user part +
/// parameters while keeping the generated (bound-socket) host:port. `emits` are
/// the `(canonical, captured_value)` pairs from
/// [`MessageTemplate::remote_target_emits`]; an empty list is the identity. Only
/// the first generated header of each name is rewritten (Contact is single; a
/// Route the stack did not generate is left to the dialog route set).
pub fn apply_remote_target_emits(
    headers: &[SipHeader],
    emits: &[(String, String)],
) -> Vec<SipHeader> {
    if emits.is_empty() {
        return headers.to_vec();
    }
    let mut out = headers.to_vec();
    for (canon, captured) in emits {
        if let Some(h) = out.iter_mut().find(|h| crate::remote_target::canonical(&h.name) == *canon)
        {
            if let Some((host, port)) = crate::remote_target::first_hostport(&h.value) {
                h.value = crate::remote_target::rewrite_hostport(captured, &host, port);
            }
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::custom::CustomParser;
    use crate::parser::SipParser;

    fn parse(raw: &[u8]) -> SipMessage {
        CustomParser::new().parse(raw).expect("well-formed")
    }

    #[test]
    fn classifies_tier1_vs_frozen_by_name() {
        assert_eq!(HeaderClass::of("Via"), HeaderClass::Regenerated);
        assert_eq!(HeaderClass::of("CALL-ID"), HeaderClass::Regenerated);
        assert_eq!(HeaderClass::of("cseq"), HeaderClass::Regenerated);
        assert_eq!(HeaderClass::of("Content-Length"), HeaderClass::Regenerated);
        assert_eq!(HeaderClass::of("Record-Route"), HeaderClass::Regenerated);
        // Content-Type is FROZEN even though Content-Length is regenerated.
        assert_eq!(HeaderClass::of("Content-Type"), HeaderClass::Frozen);
        assert_eq!(HeaderClass::of("P-Asserted-Identity"), HeaderClass::Frozen);
        assert_eq!(HeaderClass::of("X-Custom"), HeaderClass::Frozen);
    }

    #[test]
    fn from_message_preserves_casing_order_and_duplicates() {
        let raw = b"INVITE sip:bob@example.com SIP/2.0\r\n\
Via: SIP/2.0/UDP 10.0.0.1:5060;branch=z9hG4bK-abc\r\n\
Max-Forwards: 70\r\n\
From: <sip:alice@example.com>;tag=at\r\n\
To: <sip:bob@example.com>\r\n\
Call-ID: c-1@10.0.0.1\r\n\
CSeq: 1 INVITE\r\n\
Contact: <sip:alice@10.0.0.1:5060>\r\n\
p-AsSeRtEd-IdEnTiTy: <sip:+15550001@example.com>\r\n\
X-Dup: one\r\n\
X-Dup: two\r\n\
Content-Type: application/sdp\r\n\
Content-Length: 0\r\n\r\n";
        let msg = parse(raw);
        let tmpl = MessageTemplate::from_message(&msg);
        assert_eq!(tmpl.method(), Some(&Method::Invite));

        let frozen = tmpl.frozen_headers();
        // Tier-1 headers (Via/From/To/Call-ID/CSeq/Max-Forwards/Contact/
        // Content-Length) are excluded; Content-Type + the customs remain.
        let names: Vec<&str> = frozen.iter().map(|h| h.name.as_str()).collect();
        assert_eq!(names, vec!["p-AsSeRtEd-IdEnTiTy", "X-Dup", "X-Dup", "Content-Type"]);
        // Casing preserved verbatim.
        assert_eq!(frozen[0].name, "p-AsSeRtEd-IdEnTiTy");
        assert_eq!(frozen[0].value, "<sip:+15550001@example.com>");
        // Both duplicate rows preserved in order.
        assert_eq!(frozen[1].value, "one");
        assert_eq!(frozen[2].value, "two");
    }

    #[test]
    fn classifies_rfc7011_compact_forms_before_freezing() {
        // Compact tier-1 names expand and classify Regenerated — else a templated
        // compact Via/From/… would freeze and DUPLICATE on the wire.
        assert_eq!(HeaderClass::of("v"), HeaderClass::Regenerated, "v = Via");
        assert_eq!(HeaderClass::of("V"), HeaderClass::Regenerated, "case-insensitive");
        assert_eq!(HeaderClass::of("f"), HeaderClass::Regenerated, "f = From");
        assert_eq!(HeaderClass::of("t"), HeaderClass::Regenerated, "t = To");
        assert_eq!(HeaderClass::of("i"), HeaderClass::Regenerated, "i = Call-ID");
        assert_eq!(HeaderClass::of("m"), HeaderClass::Regenerated, "m = Contact");
        assert_eq!(HeaderClass::of("l"), HeaderClass::Regenerated, "l = Content-Length");
        // `c` = Content-Type is FROZEN (like its long form), as are the other
        // compact forms that map to non-tier-1 headers.
        assert_eq!(HeaderClass::of("c"), HeaderClass::Frozen, "c = Content-Type (frozen)");
        assert_eq!(HeaderClass::of("s"), HeaderClass::Frozen, "s = Subject");
        assert_eq!(HeaderClass::of("k"), HeaderClass::Frozen, "k = Supported");
        assert_eq!(HeaderClass::of("e"), HeaderClass::Frozen, "e = Content-Encoding");
        // A non-compact single char is not a compact form.
        assert_eq!(HeaderClass::of("x"), HeaderClass::Frozen);
    }

    #[test]
    fn frozen_headers_excludes_compact_tier1() {
        let tmpl = MessageTemplate::request(
            Method::Invite,
            vec![
                TemplateHeader::classified("v", "SIP/2.0/UDP 1.2.3.4:5060;branch=z9hG4bK-x"),
                TemplateHeader::classified("i", "cap@1.2.3.4"),
                TemplateHeader::classified("c", "application/sdp"),
                TemplateHeader::classified("Subject", "hi"),
            ],
            Vec::new(),
        );
        let names: Vec<String> = tmpl.frozen_headers().iter().map(|h| h.name.clone()).collect();
        // `v` and `i` are tier-1 (dropped); `c` (Content-Type) and Subject frozen.
        assert_eq!(names, vec!["c".to_string(), "Subject".to_string()]);
    }

    #[test]
    fn from_message_recovers_compact_wire_names() {
        let body = "hi";
        let raw = format!(
            "INVITE sip:bob@ex SIP/2.0\r\n\
v: SIP/2.0/UDP 1.2.3.4:5060;branch=z9hG4bK-x\r\n\
Max-Forwards: 70\r\n\
f: <sip:a@ex>;tag=at\r\n\
t: <sip:b@ex>\r\n\
i: cid@1.2.3.4\r\n\
CSeq: 1 INVITE\r\n\
m: <sip:a@1.2.3.4:5060>\r\n\
c: text/plain\r\n\
l: {}\r\n\r\n{}",
            body.len(),
            body
        );
        let msg = parse(raw.as_bytes());
        let tmpl = MessageTemplate::from_message(&msg);
        let find = |canon: &str| {
            tmpl.headers().iter().find(|h| h.name.eq_ignore_ascii_case(canon)).unwrap()
        };
        // Compact tier-1 headers: canonical name, compact wire form, Regenerated.
        assert_eq!(find("Via").wire_name.as_deref(), Some("v"));
        assert_eq!(find("Via").class, HeaderClass::Regenerated);
        assert_eq!(find("From").wire_name.as_deref(), Some("f"));
        assert_eq!(find("To").wire_name.as_deref(), Some("t"));
        assert_eq!(find("Call-ID").wire_name.as_deref(), Some("i"));
        assert_eq!(find("Contact").wire_name.as_deref(), Some("m"));
        assert_eq!(find("Content-Length").wire_name.as_deref(), Some("l"));
        // Compact Content-Type is FROZEN and emits under `c`.
        assert_eq!(find("Content-Type").wire_name.as_deref(), Some("c"));
        assert_eq!(find("Content-Type").class, HeaderClass::Frozen);
        assert_eq!(
            tmpl.frozen_headers().iter().filter(|h| h.name == "c").count(),
            1,
            "frozen Content-Type emits compact",
        );
        // A header captured full stays canonical.
        assert_eq!(find("Max-Forwards").wire_name, None);
        // regenerated_name_forms: v/f/t/i/m present; content-length excluded.
        let forms = tmpl.regenerated_name_forms();
        for pair in [("Via", "v"), ("From", "f"), ("To", "t"), ("Call-ID", "i"), ("Contact", "m")] {
            assert!(forms.contains(&(pair.0.to_string(), pair.1.to_string())), "missing {pair:?}");
        }
        assert!(
            !forms.iter().any(|(c, _)| c.eq_ignore_ascii_case("content-length")),
            "Content-Length name-form is serializer-owned, never rewritten",
        );
    }

    #[test]
    fn from_message_full_names_yield_no_wire_forms() {
        let msg = parse(
            b"INVITE sip:bob@ex SIP/2.0\r\n\
Via: SIP/2.0/UDP 1.2.3.4:5060;branch=z9hG4bK-x\r\n\
Max-Forwards: 70\r\n\
From: <sip:a@ex>;tag=at\r\n\
To: <sip:b@ex>\r\n\
Call-ID: cid@1.2.3.4\r\n\
CSeq: 1 INVITE\r\n\
Contact: <sip:a@1.2.3.4:5060>\r\n\
Content-Length: 0\r\n\r\n",
        );
        let tmpl = MessageTemplate::from_message(&msg);
        assert!(tmpl.headers().iter().all(|h| h.wire_name.is_none()), "no compact forms");
        assert!(tmpl.regenerated_name_forms().is_empty(), "nothing to rewrite");
    }

    #[test]
    fn apply_name_forms_rewrites_only_mapped_headers() {
        let headers = vec![
            SipHeader { name: "Via".into(), value: "x".into() },
            SipHeader { name: "From".into(), value: "y".into() },
            SipHeader { name: "Subject".into(), value: "z".into() },
        ];
        let forms =
            vec![("Via".to_string(), "v".to_string()), ("From".to_string(), "f".to_string())];
        let out = apply_name_forms(&headers, &forms);
        assert_eq!(out[0].name, "v");
        assert_eq!(out[1].name, "f");
        assert_eq!(out[2].name, "Subject", "unmapped header untouched");
        // Empty map = identity (today's full names).
        assert_eq!(apply_name_forms(&headers, &[]), headers);
    }

    #[test]
    fn name_matches_is_compact_aware() {
        use crate::message_helpers::name_matches;
        assert!(name_matches("Supported", "Supported"));
        assert!(name_matches("Supported", "k"), "compact Supported");
        assert!(name_matches("Supported", "K"), "compact, case-insensitive");
        assert!(name_matches("Content-Type", "c"), "compact Content-Type");
        assert!(name_matches("From", "f"));
        // Allow has no compact form; `a` must not falsely match.
        assert!(name_matches("Allow", "Allow"));
        assert!(!name_matches("Allow", "a"));
        // A different header never matches.
        assert!(!name_matches("Supported", "Require"));
        assert!(!name_matches("Supported", "x"));
    }

    #[test]
    fn regenerated_name_forms_mixed_via_collapses() {
        // A capture with one full `Via:` and one compact `v:` row (v1 boundary).
        let raw = "INVITE sip:b@ex SIP/2.0\r\n\
Via: SIP/2.0/UDP 1.1.1.1:5060;branch=z9hG4bK-1\r\n\
v: SIP/2.0/UDP 2.2.2.2:5060;branch=z9hG4bK-2\r\n\
Max-Forwards: 70\r\n\
From: <sip:a@ex>;tag=at\r\n\
To: <sip:b@ex>\r\n\
Call-ID: c@1\r\n\
CSeq: 1 INVITE\r\n\
Contact: <sip:a@1.1.1.1:5060>\r\n\
Content-Length: 0\r\n\r\n";
        let tmpl = MessageTemplate::from_message(&parse(raw.as_bytes()));
        let forms = tmpl.regenerated_name_forms();
        // Only the compact row yields a form (canonical Via -> v).
        assert_eq!(
            forms.iter().filter(|(c, _)| c.eq_ignore_ascii_case("via")).count(),
            1,
        );
        assert!(forms.contains(&("Via".to_string(), "v".to_string())));
        // apply_name_forms rewrites EVERY Via row to the one form (the collapse).
        let headers = vec![
            SipHeader { name: "Via".into(), value: "one".into() },
            SipHeader { name: "Via".into(), value: "two".into() },
        ];
        let out = apply_name_forms(&headers, &forms);
        assert_eq!(out[0].name, "v");
        assert_eq!(out[1].name, "v", "v1: both rows collapse to the compact form");
    }

    #[test]
    fn response_template_carries_status_and_reason() {
        let tmpl = MessageTemplate::response(
            486,
            "Busy Here",
            vec![TemplateHeader::frozen("Retry-After", "30")],
            Vec::new(),
        );
        assert_eq!(tmpl.status(), Some((486, "Busy Here")));
        assert_eq!(tmpl.method(), None);
        assert_eq!(tmpl.frozen_headers().len(), 1);
    }
}
